
version: 2

models:
  - name: customers
    description: "A customer dbt model"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_customers
    description: "A staging customer dbt model"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: "A staging ordering dbt model"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed','shipped','completed','return_pending','returned']
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - not_null
          - relationships:
             to: ref('stg_customers')
             field: customer_id